# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - challengeIbge

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
  APP_PATH: ./ChallengeIBGE.Api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Get Current IP Address
          id: ip
          uses: haythem/public-ip@v1.2

        - name: Add IP address to SQL Server
          run: az sql server firewall-rule create --resource-group challenge --server challengesqlserver --name ghactions --start-ip-address ${{ steps.ip.outputs.ipv4 }} --end-ip-address ${{ steps.ip.outputs.ipv4 }}

        - name: Build with dotnet
          run: dotnet build ${{ env.APP_PATH }} --configuration Release
        
        - name: dotnet publish
          run: dotnet publish ${{ env.APP_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/myapp

        - name: Install EF Tools
          run: dotnet tool install --global dotnet-ef

        - name: dotnet database update
          run: dotnet ef database update --startup-project ${{ env.APP_PATH }} -- --environment Production

        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v3
          with:
            name: .net-app
            path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'challengeIbge'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0DBB7DEF32034059956AC36644020975 }}
          package: .
